spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sample_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: your_secret_key
    expiration-time: 3600000 # 1 hour in milliseconds