spring:
  datasource:
    url: jdbc:mysql://localhost:3307/apexdb2
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
#logging:
#  level:
#    root: DEBUG

